### ISSUE TITLE
Composed URL

### ISSUE THREAD

**Issue by llrs** [elvanov/MOGAMUN#5]
Hi, I just found this packages thanks to Anaïs Baudot talk on the BSC. Great software.

I would like to note that on the [Bioconductor site](https://bioconductor.org/packages/3.12/MOGAMUN) of the package the link on the DESCRIPTION file is considered relative to the packages html sites, probably due to the quotations it has.

I suggest you use `usethis::use_github_links()` to create the links and leave the link to the pre-print for the citation, as it is also displayed on the landing page. Or remove the quotation marks and see if it fixes the automatically generated link on the landing page of Bioconductor.

**Comment by elvanov** [comment]
Hello Lluís, 

Thank you very much for the feedback on MOGAMUN and for pointing out the broken URL. It is now fixed on GitHub and on the 'devel' branch of Bioconductor, and so it will be in the next Bioconductor release.

I hope you will find MOGAMUN helpful.

Best wishes,
Elva
