### ISSUE TITLE
Error while running mogamun_run() on Windows

### ISSUE THREAD

**Issue by SimonCrouzet** [elvanov/MOGAMUN#6]
Hello,

Thanks for your work on the package.
I noticed a bug while trying to use MOGAMUN on Windows: the function mogamun_run() is using MulticoreParam(), which is not supported by Windows according to the error message: `MulticoreParam() not supported on Windows, use SnowParam()`
Would it be possible to handle a condition for using SnowParam() instead of MulticoreParam(), allowing us to either choose it with a parameter or pick the right one automatically depending of our OS?

Best,

**Comment by elvanov** [comment]
Hello Simon,

Thank you for your message and for your interest in MOGAMUN. 

Unfortunately, parallelization of MOGAMUN in Windows is not supported, as mentioned in the README file (https://github.com/elvanov/MOGAMUN/blob/master/README.md) and in the vignette. Indeed, parallelization is quite tricky in Windows. I tried your suggestion but I got other errors, so I am afraid that the current workaround is to use a single core, even if you want to run MOGAMUN several times. This means that you can set the `NumberOfRunsToExecute` parameter to any value you want, but `Cores` must be equal to 1. 

However, parallelization is possible in Unix-like operative systems (such as Linux and Mac OS). 

Best,
Elva
